version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017
  mongo-seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
        - ./initUser.json:/initUser.json
    command: 'mongoimport --host mongodb --db users --collection users --type json --file /initUser.json --jsonArray'
  rabbitmq:
    image: rabbitmq.latest
    ports:
        - 5672:5672
  user:
    build:
      context: user
    depends_on:
      - 'mongodb'
      - 'rabbitmq'
    restart: on-failure
    links:
      - 'rabbitmq'
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'topSecret'
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - ./initMovie.sql:/initMovie.sql
    command: 'mysqld --init-file=/initMovie.sql'