# https://www.pulumi.com/ai/conversations/70e866d1-88d8-4137-ad1a-e5e009f7f112
name: rabbitmq-cloudrun-service
runtime: yaml
description: A Pulumi program to create a Cloud Run service for RabbitMQ in GCP

resources:
  rabbitmq-service:
    type: gcp:cloudrun/service:Service
    properties:
      location: us-central1
      template:
        spec:
          containers:
            - image: rabbitmq:latest
      traffic:
        - percent: 100
          latestRevision: true